### ISSUE TITLE
change dependency endroid/qr-code

### ISSUE THREAD

**Issue by matodrobec** [neonbug/fiscal-verification#1]
Hello,
can you change dependency of endroid/qrcode

thx

**Comment by tadejkan** [comment]
Hey.

Change to what?
Do you mean update the dependency to a newer version, or change it to endroid/qr-code (since endroid/qrcode is marked as abandoned)?

**Comment by matodrobec** [comment]
Hello,
like the author suggests https://packagist.org/packages/endroid/qrcode

**Comment by tadejkan** [comment]
Done
